COMMON_DROP_COLUMNS = [
    "INTERNATIONAL",
    "EXAM_TYPE",
    "ADMITTED_EXAM_1",
    "ADMITTED_EXAM_2",
    "ADMITTED_EXAM_3",
    "EXAMS_SUM",
    "PP",
    "ORIGINAL_DOCUMENT",
    "ADMITTED_SUBJECT_PRIZE",
    "MEAN_STATE_EXAM",
    "MEAN_ADMITTED_STATE_EXAM",
    "SUM_STATE_EXAM",
    "STATE_EXAM_SUBJECT_1",
    "STATE_EXAM_SUBJECT_2",
    "STATE_EXAM_SUBJECT_3",
    "PLAN_1",
    "PLAN_2",
    "PLAN_3",
    "OP_1",
    "OP_2",
    "OP_3",
    "CRIMEA",
    "DORMITORY_FOR_EXAMS",
    "MACRO_POSTCODE",
    "LAST_ORDER_DATE",
    "YEAR_EDITION",
    "FEE_TYPE_1",
    "FEE_TYPE_2",
    "FEE_TYPE_3",
    "GROUPS_SEM_1",
    "GROUPS_SEM_2",
    "GROUPS_SEM_3",
    "GROUPS_SEM_4",
    "GROUPS_SEM_5",
    "GROUPS_SEM_6",
    "GROUPS_SEM_7",
    "GROUPS_SEM_8",
    "PLAN_SEM_1",
    "PLAN_SEM_2",
    "PLAN_SEM_3",
    "PLAN_SEM_4",
    "PLAN_SEM_5",
    "PLAN_SEM_6",
    "PLAN_SEM_7",
    "PLAN_SEM_8",
    "OP_SEM_1",
    "OP_SEM_2",
    "OP_SEM_3",
    "OP_SEM_4",
    "OP_SEM_5",
    "OP_SEM_6",
    "OP_SEM_7",
    "OP_SEM_8",
    "FAC_SEM_1",
    "FAC_SEM_2",
    "FAC_SEM_3",
    "FAC_SEM_4",
    "FAC_SEM_5",
    "FAC_SEM_6",
    "FAC_SEM_7",
    "FAC_SEM_8",
    "INTERRUPT_SEM_1",
    "INTERRUPT_SEM_2",
    "INTERRUPT_SEM_3",
    "INTERRUPT_SEM_4",
    "INTERRUPT_SEM_5",
    "INTERRUPT_SEM_6",
    "INTERRUPT_SEM_7",
    "INTERRUPT_SEM_8",
    "MARKS_MEAN_SEM_3",
    "MARKS_MEAN_SEM_4",
    "MARKS_MEAN_SEM_5",
    "MARKS_MEAN_SEM_6",
    "MARKS_MEAN_SEM_7",
    "MARKS_MEAN_SEM_8",
    "DEBTS_NUMBER_SEM_1",
    "DEBTS_NUMBER_SEM_2",
    "DEBTS_NUMBER_SEM_3",
    "DEBTS_NUMBER_SEM_4",
    "DEBTS_NUMBER_SEM_5",
    "DEBTS_NUMBER_SEM_6",
    "DEBTS_NUMBER_SEM_7",
    "DEBTS_NUMBER_SEM_8",
]

MODEL_DROP_COLUMNS = [
    "HONS_TARGET",
    "DROPPED_TARGET",
    "ISU_ID",
    "MARKS_MEAN_SEM_1",
    "MARKS_MEAN_SEM_2",
    "CURRENT_STATUS",
    "REGION_ID",
    "START_YEAR",
]
STATE_EXAMS = [
    "RUSSIAN_LANG",
    "MATH",
    "PHYSICS",
    "CHEMISTRY",
    "FOREIGN_LANG",
    "INFORMATICS",
    "SOCIAL_STUDIES",
]

COLS_TRANSLATION = {
    "GENDER": "GENDER",
    "ADMITTED_EXAMS_SUM": "ADMITTED_EXAMS_SUM",
    "RUSSIAN_LANG": "RUSSIAN_LANG",
    "MATH": "MATH",
    "PHYSICS": "PHYSICS",
    "CHEMISTRY": "CHEMISTRY",
    "FOREIGN_LANG": "FOREIGN_LANG",
    "INFORMATICS": "INFORMATICS",
    "SOCIAL_STUDIES": "SOCIAL_STUDIES",
    "DROPPED_BEFORE": "DROPPED_BEFORE",
    "START_YEAR": "START_YEAR",
    "AGE_AT_START": "AGE_AT_START",
    "MARKS_MEAN_SEM_1": "MARKS_MEAN_SEM_1",
    "PROGRAM_01": "PROGRAM_01",
    "PROGRAM_09": "PROGRAM_09",
    "PROGRAM_10": "PROGRAM_10",
    "PROGRAM_11": "PROGRAM_11",
    "PROGRAM_12": "PROGRAM_12",
    "PROGRAM_13": "PROGRAM_13",
    "PROGRAM_14": "PROGRAM_14",
    "PROGRAM_15": "PROGRAM_15",
    "PROGRAM_16": "PROGRAM_16",
    "PROGRAM_18": "PROGRAM_18",
    "PROGRAM_19": "PROGRAM_19",
    "PROGRAM_23": "PROGRAM_23",
    "PROGRAM_24": "PROGRAM_24",
    "PROGRAM_27": "PROGRAM_27",
    "PROGRAM_38": "PROGRAM_38",
    "PROGRAM_44": "PROGRAM_44",
    "PROGRAM_45": "PROGRAM_45",
    "ADMISSION_COND_без вступительных испытаний": "ADMISSION_COND_without entrance exams",
    "ADMISSION_COND_на бюджетное место в пределах особой квоты": "ADMISSION_COND_on budget place by special quota",
    "ADMISSION_COND_на бюджетное место в пределах целевой квоты": "ADMISSION_COND_on budget place by target quota",
    "ADMISSION_COND_на выделенное бюджетное место (для жителей Крыма)": "ADMISSION_COND_on allocated budget place (Crimea)",
    "ADMISSION_COND_на контрактной основе": "ADMISSION_COND_on contractual basis",
    "ADMISSION_COND_по общему конкурсу": "ADMISSION_COND_by regular admission",
    "RUSSIAN_LANG_BIN": "RUSSIAN_LANG_BIN",
    "MATH_BIN": "MATH_BIN",
    "PHYSICS_BIN": "PHYSICS_BIN",
    "CHEMISTRY_BIN": "CHEMISTRY_BIN",
    "FOREIGN_LANG_BIN": "FOREIGN_LANG_BIN",
    "INFORMATICS_BIN": "INFORMATICS_BIN",
    "SOCIAL_STUDIES_BIN": "SOCIAL_STUDIES_BIN",
    "Физика": "Physics",
    "nan": "nan",
    "Иностранный язык": "Foreign language",
    "Химия": "Chemistry",
    "Русский язык": "Russian language",
    "Биология": "Biology",
    "Информатика": "Informatics",
    "Обществознание": "Social studies",
    "Математика": "Mathematics",
    "ADMISSION_TYPE_100 баллов за олимпиаду": "ADMISSION_TYPE_100 points for olympiad",
    "ADMISSION_TYPE_ЕГЭ": "ADMISSION_TYPE_USE",
    "ADMISSION_TYPE_nan": "ADMISSION_TYPE_nan",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_0.0": "ADMITTED_SUBJECT_PRIZE_LEVEL_0.0",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_1.0": "ADMITTED_SUBJECT_PRIZE_LEVEL_1.0",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_2.0": "ADMITTED_SUBJECT_PRIZE_LEVEL_2.0",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_3.0": "ADMITTED_SUBJECT_PRIZE_LEVEL_3.0",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_4.0": "ADMITTED_SUBJECT_PRIZE_LEVEL_4.0",
    "ADMITTED_SUBJECT_PRIZE_LEVEL_nan": "ADMITTED_SUBJECT_PRIZE_LEVEL_nan",
    "ADMITTED_EXAMS_SUM_BIN": "ADMITTED_EXAMS_SUM_BIN",
    "NATIONALITY_Белоруссия": "NATIONALITY_Belorussia",
    "NATIONALITY_Вьетнам": "NATIONALITY_Vietnam",
    "NATIONALITY_КНР": "NATIONALITY_PRC",
    "NATIONALITY_Казахстан": "NATIONALITY_Kazakhstan",
    "NATIONALITY_Киргизия": "NATIONALITY_Kyrgyzstan",
    "NATIONALITY_Российская Федерация": "NATIONALITY_Russian Federation",
    "NATIONALITY_Таджикистан": "NATIONALITY_Tajikistan",
    "NATIONALITY_Туркмения": "NATIONALITY_Turkmenistan",
    "NATIONALITY_Узбекистан": "NATIONALITY_Uzbekistan",
    "NATIONALITY_Украина": "NATIONALITY_Ukraine",
    "NATIONALITY_другая страна": "NATIONALITY_another country",
    "MACRO_BIRTH_PLACE_архангельск и ао": "MACRO_BIRTH_PLACE_arkhangelsk",
    "MACRO_BIRTH_PLACE_белоруссия": "MACRO_BIRTH_PLACE_belorussia",
    "MACRO_BIRTH_PLACE_волгоград и во": "MACRO_BIRTH_PLACE_volgograd",
    "MACRO_BIRTH_PLACE_воронеж и во": "MACRO_BIRTH_PLACE_voronezh",
    "MACRO_BIRTH_PLACE_вьетнам": "MACRO_BIRTH_PLACE_vietnam",
    "MACRO_BIRTH_PLACE_другая страна": "MACRO_BIRTH_PLACE_another country",
    "MACRO_BIRTH_PLACE_другой город (РФ)": "MACRO_BIRTH_PLACE_another city (Russia)",
    "MACRO_BIRTH_PLACE_екатеринбург и со": "MACRO_BIRTH_PLACE_ekaterinburg",
    "MACRO_BIRTH_PLACE_ижевск и ио": "MACRO_BIRTH_PLACE_izhevsk",
    "MACRO_BIRTH_PLACE_иркутс и ио": "MACRO_BIRTH_PLACE_irkutsk",
    "MACRO_BIRTH_PLACE_казань и рт": "MACRO_BIRTH_PLACE_kazan",
    "MACRO_BIRTH_PLACE_казахстан": "MACRO_BIRTH_PLACE_kazakhstan",
    "MACRO_BIRTH_PLACE_киргизия": "MACRO_BIRTH_PLACE_kyrgyzstan",
    "MACRO_BIRTH_PLACE_кнр": "MACRO_BIRTH_PLACE_prc",
    "MACRO_BIRTH_PLACE_красноярск и кк": "MACRO_BIRTH_PLACE_kransoyarsk",
    "MACRO_BIRTH_PLACE_москва и мо": "MACRO_BIRTH_PLACE_moscow",
    "MACRO_BIRTH_PLACE_мурманск и мо": "MACRO_BIRTH_PLACE_murmansk",
    "MACRO_BIRTH_PLACE_нижний новгород и но": "MACRO_BIRTH_PLACE_nizhny_novgorod",
    "MACRO_BIRTH_PLACE_новосибирск и но": "MACRO_BIRTH_PLACE_novosibirsk",
    "MACRO_BIRTH_PLACE_оренбург и оо": "MACRO_BIRTH_PLACE_orenburg",
    "MACRO_BIRTH_PLACE_пермь и пк": "MACRO_BIRTH_PLACE_perm",
    "MACRO_BIRTH_PLACE_петрозаводск и рк": "MACRO_BIRTH_PLACE_petrozavodsk",
    "MACRO_BIRTH_PLACE_ростов-на-дону и ро": "MACRO_BIRTH_PLACE_rostov-on-don",
    "MACRO_BIRTH_PLACE_самара и со": "MACRO_BIRTH_PLACE_samara",
    "MACRO_BIRTH_PLACE_санкт-петербург и ло": "MACRO_BIRTH_PLACE_saint-petersburg",
    "MACRO_BIRTH_PLACE_саратов и со": "MACRO_BIRTH_PLACE_saratov",
    "MACRO_BIRTH_PLACE_таджикистан": "MACRO_BIRTH_PLACE_tajikistan",
    "MACRO_BIRTH_PLACE_томск и то": "MACRO_BIRTH_PLACE_tomsk",
    "MACRO_BIRTH_PLACE_туркмения": "MACRO_BIRTH_PLACE_turkmenistan",
    "MACRO_BIRTH_PLACE_узбекистан": "MACRO_BIRTH_PLACE_uzbekistan",
    "MACRO_BIRTH_PLACE_украина": "MACRO_BIRTH_PLACE_ukraine",
    "MACRO_BIRTH_PLACE_уфа и рб": "MACRO_BIRTH_PLACE_ufa",
    "MACRO_BIRTH_PLACE_челябинск и чо": "MACRO_BIRTH_PLACE_chelyabinsk",
    "SCHOLARSHIP_TYPE_Бронзовый ЕГЭ": "SCHOLARSHIP_TYPE_Bronze USE",
    "SCHOLARSHIP_TYPE_Золотой ЕГЭ": "SCHOLARSHIP_TYPE_Gold USE",
    "SCHOLARSHIP_TYPE_Золотой Олимпиада": "SCHOLARSHIP_TYPE_Gold Olympiad",
    "SCHOLARSHIP_TYPE_Серебряный ЕГЭ": "SCHOLARSHIP_TYPE_Silver USE",
    "SCHOLARSHIP_TYPE_Серебряный Олимпиада": "SCHOLARSHIP_TYPE_Silver Olympiad",
    "SCHOLARSHIP_TYPE_nan": "SCHOLARSHIP_TYPE_nan",
    "DORMITORY_FOR_STUDY_0.0": "DORMITORY_FOR_STUDY_0.0",
    "DORMITORY_FOR_STUDY_1.0": "DORMITORY_FOR_STUDY_1.0",
    "DORMITORY_FOR_STUDY_nan": "DORMITORY_FOR_STUDY_nan"
}

# region names english cast dictionary
REGION_TRANSLATION = {"Moscow" : "москва и мо",
            "Moscow region":"москва и мо",
            "Republic of Bashkortostan" : "уфа и рб",
            "St. Petersburg": "санкт-петербург и ло",
             "Leningrad region": "санкт-петербург и ло",
             "Chelyabinsk region": "челябинск и чо",
             "Krasnoyarsk region": "красноярск и кк",
             "Murmansk region": "мурманск и мо",
             "Sverdlovsk region": "екатеринбург и со",
             "Arkhangelsk region": "архангельск и ао",
             "Irkutsk region":"иркутск и ио",
             "Samara Region": "самара и со",
              "Perm":  "пермь и пк",
             "Republic of Tatarstan": "казань и рт",
             "Saratov region": "саратов и со",
             "Nizhny Novgorod Region": "нижний новгород и но",
             "Rostov region": "ростов-на-дону и ро",
             "The Republic of Karelia": "петрозаводск и рк",
             "Orenburg region": "оренбург и оо",
             "Novosibirsk region": "новосибирск и но",
             "Volgograd region": "волгоград и во",
             "Udmurt republic": "ижевск и ру",
             "Tomsk region" : "томск и то",
             "Voronezh region": "воронеж и во",
             "Omsk region": "омск и оо",
             "Krasnodar region": "краснодар и кк",
             "Komi Republic": "сыктывкар и рк",
             "Kemerovo region": "кемерово и ко",
             "Yaroslavl region":"ярославль и яо",
             "Kaliningrad region": "калининград и ко",
             "Ulyanovsk region": "ульяновск и уо",
             "Khabarovsk region": "хабаровск и хк",
             "Primorsky Krai": "владивосток и пк",
             "Chuvash Republic": "чебоксары и чр",
             "Pskov region": "псков и по",
             "Vologda Region":"вологда и во",
             "Tyumen region": "тюмень и то",
             "Oryol Region": "орел и оо",
             "Kirov region": "киров и ко",
             "The Republic of Mordovia": "саранск и рм",
             "Mari El Republic": "йошкар-ола и рмэ",
             "Astrakhan region": "астрахань и ао",
#              "Smolensk region": "смоленск и со",
             "Penza region": "пенза и по",
             "Zabaykalsky Krai": "чита и зк",
             "The Republic of Buryatia": "улан-удэ и рб",
             "Belgorod region": "белгород и бо",
             "Kurgan region": "курган и ко",
             "Ivanovo region": "иваново и ио",
             "The Republic of Sakha (Yakutia)":"якутск и рс",
             "Stavropol region": "ставрополь и ск",
             "Kostroma region": "кострома и ко",
             "Kamchatka Krai" : "петропавловск-камчатский и кк",
             "Kaluga region": "калуга и ко",
             "Yamalo-Nenets Autonomous Okrug": "салехард и янао",
             "The Republic of Khakassia": "абакан и рх",
             "Altai Republic" : "барнаул и ак",
             "Tambov Region": "тамбов и то",
             "Khanty-Mansiysk": "сургут и хмао",
             "The Republic of Dagestan": "махачкала и рд",
#              "Chechen Republic": "грозный и рч",
             "Vladimir region": "владимир и во",
             "Bryansk region": "брянск и бо"
            }